// 크라쿠프 워킹 투어 — 12 정거장 (코스 A)
// 좌표: OpenStreetMap Nominatim 검증 (2026-05-18)
window.TOUR_DATA = {
  meta: {
    title: '크라쿠프 가이드 투어',
    subtitle: '중앙역 → 쉰들러 공장 · 도보 6km · 12정거장',
    totalKm: '~6 km',
    totalTime: '4–5h',
    stopsCount: 12,
  },
  stops: [
    {
      id: 's01', num: '01', order: 1,
      time: '출발 · 0:00', stay: null,
      nameKr: '크라쿠프 중앙역', namePl: 'Kraków Główny',
      lat: 50.0684238, lon: 19.9478862,
      image: 'krakow/images/01-glowny-station.jpg',
      paragraphs: [
        '1847년 개관한 폴란드의 가장 오래된 주요 역 중 하나. 19세기 부분과 2014년 개축된 현대 부분이 한 자리에 공존한다. 바르샤바·자코파네·아우슈비츠(오시비엥침) 등 모든 방향의 폴란드 도시 기차가 여기서 출발/도착한다.',
        '역 광장의 이름이 흥미롭다 — <em>plac Jana Nowaka-Jeziorańskiego</em>. 2회차에서 본 폴란드 국내군의 한 전령(<em>kurier</em>) 얀 노박-예지오란스키의 이름이다. 첫 정거장에서부터 이 도시가 폴란드 역사와 어떻게 얽혀 있는지가 시작된다.',
      ],
      walkAfter: { mode: '도보 5분', tram: false, text: '역 광장에서 남쪽으로 약 300m. 큰 길(<em>Basztowa</em>)을 건너면 옛 성벽 유적이 나타난다.' },
    },
    {
      id: 's02', num: '02', order: 2,
      time: '0:10', stay: '약 15분',
      nameKr: '바르비칸 · 플로리안 문', namePl: 'Barbakan · Brama Floriańska',
      lat: 50.065458, lon: 19.941451,
      image: 'krakow/images/02-barbican-florian.jpg',
      paragraphs: [
        '구시가지로 들어가는 옛 문. <strong>플로리안 문(Brama Floriańska)</strong>은 14세기에 세워진 도시 8개 문 중 유일하게 살아남은 한 문이다. 그 앞에 <strong>바르비칸(Barbakan)</strong>이 — 1499년 추가 방어용으로 — 솟아 있다. 둥글고 두꺼운 벽돌 성탑, 7개의 망루.',
        '바르샤바의 바르비칸과 이름은 같지만, 크라쿠프의 바르비칸이 <strong>유럽에서 가장 큰 보존 바르비칸 중 하나</strong>다. 200명의 수비대가 들어갈 수 있던 규모.',
        '플로리안 문을 통과하면 — 13세기 격자 도시계획의 한가운데로 — 발이 들어선다.',
        '<strong>관광 팁:</strong> 바르비칸은 4–10월 입장 가능(약 15 PLN). 안에 들어가 망루를 둘러볼 수 있다.',
      ],
      walkAfter: { mode: '도보 5분', tram: false, text: '플로리안 문을 통과해 곧장 남쪽으로 — 그 길이 바로 다음 정거장.' },
    },
    {
      id: 's03', num: '03', order: 3,
      time: '0:25', stay: '약 15분',
      nameKr: '플로리안스카 거리', namePl: 'Ulica Floriańska',
      lat: 50.0634113, lon: 19.9402619,
      image: 'krakow/images/03-florianska-street.jpg',
      paragraphs: [
        '플로리안 문에서 중앙광장까지 약 350m의 거리. <strong>왕의 길(Droga Królewska)</strong>의 시작 구간이다. 폴란드 왕들이 즉위식을 위해 바벨로 향할 때, 외국 대사들이 입성할 때, 이 길을 지나갔다.',
        '거리 양옆은 13–16세기 건물들. 19세기 후반에 폴란드의 가장 유명한 카페가 여기 모였다 — <strong>Jama Michalika</strong>(1895)는 폴란드 모더니즘 예술가들이 모이던 자리. 입구 옆 작은 박물관 입장이 가능하며, 폴란드 19세기 후반 문학·미술의 한 자리를 본다.',
        '거리 끝, 중앙광장 직전에 — 화면 정면에 — 두 개의 다른 높이의 탑이 솟아 있다. 다음 정거장.',
      ],
      walkAfter: { mode: '도보 1분', tram: false, text: '곧 광장 입구. 큰 광장이 열리며 한가운데 긴 르네상스 건물이 보인다.' },
    },
    {
      id: 's04', num: '04', order: 4,
      time: '0:42', stay: '약 30분',
      nameKr: '중앙광장 · 직물회관', namePl: 'Rynek Główny · Sukiennice',
      lat: 50.0617012, lon: 19.9373511,
      image: 'krakow/images/04-rynek-sukiennice.jpg',
      paragraphs: [
        '7회차 Beat 2에서 본 그 광장. 약 200m × 200m, 유럽 최대급 중세 광장. 1257년 격자 도시계획의 중심.',
        '광장 한가운데를 가로지르는 르네상스 양식의 긴 건물이 <strong>직물회관(Sukiennice)</strong>. 1층은 호박·민속 공예·기념품 시장(반드시 들러볼 가치 있음), 2층은 <strong>19세기 폴란드 회화관</strong> — 2회차의 얀 마테이코, 폴란드 사실주의의 거장들 작품이 모인 자리.',
        '광장 북쪽 한 모서리에 <strong>시청 탑(Wieża Ratuszowa)</strong>이 외로이 서 있다. 옛 시청이 1820년 철거된 뒤 탑만 남았다. 전망대 입장 가능.',
        '<strong>관광 팁:</strong> 광장의 카페에 한 번 앉아본다. 직물회관 1층에서는 호박 보석 가격을 두 군데 이상 비교하기를 권한다.',
      ],
      walkAfter: { mode: '도보 1분', tram: false, text: '광장 동쪽 끝 — 두 다른 높이의 탑이 솟은 성당으로.' },
    },
    {
      id: 's05', num: '05', order: 5,
      time: '1:15', stay: '약 25분',
      nameKr: '성 마리아 성당 · 헤이나우 트럼펫', namePl: 'Kościół Mariacki',
      lat: 50.0616547, lon: 19.9394485,
      image: 'krakow/images/05-mariacka-towers.jpg',
      paragraphs: [
        '14세기 후반 벽돌 고딕 성당. 광장 위로 솟은 두 탑의 높이가 다른데(한 탑이 81m로 약 12m 더 높다), 14세기 전설이 — 두 형제 건축가가 경쟁하다 한 명이 자기 형제를 살해하고 자살했다고 — 설명한다. 사실 두 탑의 용도가 달라서다(높은 탑은 도시 감시탑, 낮은 탑은 종탑).',
        '4회차에서 본 <strong>헤이나우(Hejnał Mariacki)</strong>가 매시간 정각에 높은 탑에서 시작된다. 트럼펫 연주자가 4방위로 같은 멜로디를 부는데, 멜로디가 — 13세기 몽골 침공 때 화살에 맞고 죽은 트럼펫 연주자를 기리며 — 한가운데에서 갑자기 끊긴다. 폴란드 어린이라면 모두 아는 이야기.',
        '성당 내부에는 <strong>비트 슈토슈(Veit Stoss)</strong>의 — 15세기 후반 — 거대한 목조 제단(<em>Ołtarz Mariacki</em>)이 있다. 약 13m 높이, 200개 이상의 조각상. 2차 대전 점령기에 독일로 약탈되었으나 종전 후 반환되었다. 폴란드 고딕 미술의 정점.',
        '<strong>관광 팁:</strong> 본당 입장 약 15 PLN. 매시간 정각 헤이나우 시간에 광장에 있는 게 좋다.',
      ],
      walkAfter: { mode: '도보 5분', tram: false, text: '광장에서 남서쪽으로 — 좁은 골목 약 300m. <em>Jagiellońska</em> 거리.' },
    },
    {
      id: 's06', num: '06', order: 6,
      time: '1:45', stay: '약 20분',
      nameKr: '콜레기움 마이우스', namePl: 'Collegium Maius',
      lat: 50.0615630, lon: 19.9334091,
      image: 'krakow/images/06-collegium-maius.jpg',
      paragraphs: [
        '7회차에서 본 야기엘론스키 대학의 가장 오래된 건물. 1400년대 초 후기 고딕 양식. 안뜰의 3층 회랑이 폴란드에서 가장 유명한 안뜰 중 하나.',
        '<strong>3회차의 코페르니쿠스가 1491년 입학해 이 안뜰에서 공부했다.</strong> 같은 안뜰을 — 약 450년 후 — <strong>카롤 보이티와</strong>가 1938년 입학생으로 거닐었다. 그가 점령기 중에도 비밀 학업을 이어간 자리이기도 하다.',
        '현재 건물은 <strong>대학 박물관</strong>이다. 코페르니쿠스가 사용한 천문 도구들이 일부 보관되어 있다. 매시간 정각, 안뜰의 시계 위에서 작은 인형들이 음악과 함께 돌아간다 — 잠깐 멈춰 볼 가치 있음.',
        '<strong>관광 팁:</strong> 박물관 내부 입장은 가이드 투어 형식(약 20 PLN), 영어 가이드도 있음. 안뜰 자체는 무료로 들어갈 수 있다.',
      ],
      walkAfter: { mode: '도보 12분', tram: false, text: '남쪽으로 약 800m. <em>Grodzka</em> 거리(<strong>왕의 길</strong>의 후반부)를 따라 — 1257년 격자도시의 메인 도로 — 곧장 가면 바벨 언덕이 시야에 들어온다.' },
    },
    {
      id: 's07', num: '07', order: 7,
      time: '2:20', stay: '약 40분',
      nameKr: '바벨 성', namePl: 'Zamek Królewski na Wawelu',
      lat: 50.0544051, lon: 19.9360223,
      image: 'krakow/images/07-wawel-castle.jpg',
      paragraphs: [
        '7회차에서 본 바벨 왕궁. 14세기 카지미에시 대왕 때 고딕으로 시작, 16세기 지그문트 1세 때 — 이탈리아 건축가들의 손으로 — 폴란드 르네상스의 정점이 되었다.',
        '안뜰의 3층 르네상스 회랑은 — 콜레기움 마이우스와 달리 — 더 화려하고 더 이탈리아적이다. 안뜰 자체는 무료 입장. 그 안의 박물관(왕실 거주 공간·무기실·동방 회화관·왕실 보물고)은 별도 티켓.',
        '<strong>관광 팁:</strong> 박물관 모든 섹션을 다 보면 2시간 이상. 4–5시간 코스 A 일정에는 안뜰 + 르네상스 안뜰 사진 + 다음 정거장(대성당)이 자연스럽다. 박물관 깊이 들어갈 거면 별도 일정으로.',
      ],
      walkAfter: { mode: '도보 2분', tram: false, text: '같은 언덕 위, 왕궁 안뜰 옆.' },
    },
    {
      id: 's08', num: '08', order: 8,
      time: '3:05', stay: '약 30분',
      nameKr: '바벨 대성당', namePl: 'Katedra Wawelska',
      lat: 50.0546504, lon: 19.9354554,
      image: 'krakow/images/08-wawel-cathedral.jpg',
      paragraphs: [
        '7회차에서 본 폴란드 왕 17명의 무덤. 1320년 봉헌. 폴란드 종묘 + 충정사의 자리.',
        '입구 옆 — 시대를 가로지르는 — 거대한 동물 뼈가 사슬에 매달려 있다. 전설에 따르면 그 뼈가 바벨에 살던 용의 뼈고, 그 뼈가 있는 한 폴란드도 존재한다. 폴란드인이 작은 미소로 가르쳐 주는 한 자리.',
        '내부에서는 — 본당 옆 작은 예배당들마다 한 명의 폴란드 왕이 묻혀 있고 — 가장 화려한 한 예배당이 <strong>지그문트 예배당(Kaplica Zygmuntowska)</strong>. 폴란드 르네상스 최고의 작품으로 평가받는다.',
        '지하 묘소(Krypty)는 별도 티켓. 가장 무거운 한 자리는 — <strong>아담 미츠키에비치의 무덤</strong>과 <strong>유제프 피우수트스키의 무덤</strong>이다. 3·5회차의 두 인물.',
        '<strong>관광 팁:</strong> 대성당 본당 입장과 지하 묘소 입장은 별도 티켓(통합 약 25 PLN). 종탑 입장도 가능하다(가파른 계단). 모든 입장은 본당 옆 매표소.',
      ],
      walkAfter: { mode: '도보 7분', tram: false, text: '바벨 언덕 동쪽 출구로 내려가면 비스와 강가의 길이 펼쳐진다. 강가를 따라 동쪽으로 약 300m.' },
    },
    {
      id: 's09', num: '09', order: 9,
      time: '3:40', stay: '약 10분',
      nameKr: '비스와 강변 · 바벨의 용', namePl: 'Smok Wawelski',
      lat: 50.0535, lon: 19.9325,
      image: 'krakow/images/09-wawel-dragon.jpg',
      paragraphs: [
        '7회차의 그 용 전설. 청동 동상은 1972년 작품으로, 가스 파이프 연결로 — 매 5분마다 — 불을 뿜는다. 도시의 가장 사진 찍히는 자리 중 하나, 그리고 폴란드 어린이들이 가장 즐거워하는 자리.',
        '여기서 비스와 강변을 한 번 둘러보는 것이 좋다. 강 위 다리 너머가 — 다음 정거장의 — 카지미에시 지구다.',
      ],
      walkAfter: { mode: '도보 12분', tram: false, text: '강가를 따라 동쪽으로 약 900m. 또는 짧은 다리를 건너 카지미에시 지구로 진입. 카지미에시 중심까지 — 시청 거리(<em>Stradomska</em>) 또는 — 강가에서 직접.' },
    },
    {
      id: 's10', num: '10', order: 10,
      time: '4:05', stay: '약 25분 (점심 옵션)',
      nameKr: '카지미에시 · 플라츠 노비', namePl: 'Kazimierz · Plac Nowy',
      lat: 50.0517373, lon: 19.9446185,
      image: 'krakow/images/10-plac-nowy.jpg',
      paragraphs: [
        '7회차 Beat 3의 그 카지미에시. <strong>플라츠 노비(Plac Nowy)</strong>는 옛 유대인 시장 광장. 한가운데 둥근 건물(<em>Okrąglak</em>)이 옛 코셔 도축장. 지금은 작은 음식 부스들이 — 폴란드의 한 음식 명물 — <strong>자피에칸카(zapiekanka)</strong>를 판다. 길쭉한 바게트 반쪽 위에 치즈와 토핑을 얹어 구운 폴란드식 패스트푸드. 한 끼 점심으로 자주 선택된다.',
        '광장 주변에 카페·바·갤러리가 빼곡하다. 카지미에시의 가장 활기 있는 자리. 오후가 가까워질수록 사람이 많아진다.',
        '<strong>점심 추천:</strong><ul><li><strong>Plac Nowy 자피에칸카</strong> 부스 — 5–7 PLN, 빠른 한 끼</li><li><strong>Hamsa</strong> (이스라엘 음식점) — 카지미에시 분위기에 맞는 곳</li><li><strong>Polakowski</strong> — 폴란드 가정식, 가격대 합리적</li><li><strong>Klezmer-Hois</strong> — 옛 미크바 건물 안의 폴란드-유대 식당, 분위기 진하다</li></ul>',
      ],
      walkAfter: { mode: '도보 5분', tram: false, text: '플라츠 노비에서 동쪽 셰로카 거리(<em>Szeroka</em>)로 약 300m. 카지미에시의 중심 거리.' },
    },
    {
      id: 's11', num: '11', order: 11,
      time: '4:35', stay: '약 30분',
      nameKr: 'Remah 시나고그와 묘지', namePl: 'Synagoga Remuh · Stary Cmentarz Żydowski',
      lat: 50.0526493, lon: 19.9472939,
      image: 'krakow/images/11-remah-synagogue.jpg',
      paragraphs: [
        '1553년 — 폴란드 가장 오래된 시나고그 중 하나. 그 옆 묘지는 — 16세기부터 19세기 초까지 — 카지미에시 유대인들의 묘지였다. 점령기에 독일군이 묘비를 부숴 길바닥 포장에 썼으나, 종전 후 일부를 발굴해 — <strong>"통곡의 벽(Ściana Płaczu)"</strong>이라 부르는 — 벽 하나로 모아 세웠다. 부서진 묘비 조각들이 모자이크처럼 박혀 있다.',
        '묘지 안에 폴란드 유대 학문의 가장 큰 인물 중 한 명 <strong>랍비 모세 이세를레스(Moses Isserles, 1525–1572)</strong>의 묘가 있다. 그의 호 <em>Remah</em>가 곧 이 시나고그와 묘지의 이름이다.',
        '입장 약 20 PLN, 남성은 키파(머리 덮개) 착용 의무. 매표소에서 빌릴 수 있음.',
        '여기까지가 코스 A의 도보 구간. 다음 정거장(쉰들러 공장)으로의 이동은 — 강을 건너야 하니 — <strong>트램 1회</strong>를 권한다.',
      ],
      walkAfter: { mode: '트램 약 15분', tram: true, text: '카지미에시에서 비스와 강을 건너 포드구제 지구. <strong>도보로는 약 20분(1.4km)</strong>도 가능하나, 4–5시간 일정에서는 트램이 효율적. 가장 가까운 정거장에서 <strong>트램 3·9·24·50</strong> 등으로 두 정거장. 하차역 <em>Plac Bohaterów Getta</em>(빈 의자 광장) 또는 — 박물관 더 가까이 — <em>SS Cyryla i Metodego</em>. 7회차에서 본 빈 의자 광장에 잠깐 들렀다 박물관으로 도보 5분도 좋다.' },
    },
    {
      id: 's12', num: '12', order: 12, terminus: true,
      time: '5:00', stay: '약 1.5–2시간',
      nameKr: '쉰들러 공장 박물관', namePl: 'Fabryka Schindlera · Muzeum Krakowa "1939–1945"',
      lat: 50.0474554, lon: 19.9617094,
      image: 'krakow/images/12-schindler-factory.jpg',
      paragraphs: [
        '7회차에서 본 그 자리. 오스카 쉰들러의 옛 에마일리아 공장이 2010년부터 <strong>"크라쿠프 1939–1945" 박물관</strong>으로 운영된다. 박물관은 쉰들러 개인 이야기보다 <strong>1939–45년 점령기 크라쿠프 도시 전체의 일상</strong>을 더 비중 있게 다룬다.',
        '전시는 시간순으로 — 1939년 9월 침공의 한 거리에서 시작해, 점령기 폴란드인의 일상, 1941년 게토 설치, 1943년 게토 청산, 그리고 종전을 따라간다. 폴란드 박물관 중에서도 가장 강력한 몰입형 전시 중 하나로 평가받는다.',
        '한 자리 — 박물관 끝의 <strong>"선택의 공간"</strong>. 점령기 폴란드인들이 — 협조·저항·구조의 — 어떤 결정을 했는지 사례를 보여주는 방. 가장 무거운 한 자리.',
        '<strong>관광 팁:</strong> 사전 예약 권장(특히 주말). 입장료 약 35 PLN. 화요일 무료(혼잡함). 음성 가이드(영어·폴란드어) 권장. 평일 늦은 오후가 한가하다.',
        '<strong>여기서 코스 A — 그리고 8회 시리즈의 마지막 — 가 마친다.</strong>',
      ],
      walkAfter: null,
    },
  ],
};
