// 자코파네 워킹 투어 — 9 정거장 (시내 도보)
// 좌표: OpenStreetMap / 폴란드 공식 자료 기반 (2026-05-22)
window.TOUR_DATA = {
  meta: {
    title: '자코파네 가이드 투어',
    subtitle: '기차역 → 굴루부프카 케이블카 · 시내 도보 3–4km · 9정거장',
    totalKm: '~3–4 km',
    totalTime: '3–4h',
    stopsCount: 9,
  },
  stops: [
    {
      id: 's01', num: '01', order: 1,
      time: '출발 · 0:00', stay: null,
      nameKr: '자코파네 기차역', namePl: 'Dworzec PKP Zakopane',
      lat: 49.3002, lon: 19.9575,
      image: 'zakopane/images/01-zakopane-station.jpg',
      paragraphs: [
        '9회차 Beat 1에서 본 그 1899년 철도의 종착역. 처음 역사 건물은 분할기 갈리시아 양식이었으나, 2017년 현대식 건물로 재건되었다. 자코파네에 들어오는 거의 모든 폴란드인이 — 한 번은 — 이 한 자리를 거친다.',
        '역 광장에서 시내(크루포브키)까지는 도보 10–15분, 약 700m. 기차역 옆에 — 같은 건물 단지로 — <strong>버스 터미널(Dworzec Autobusowy)</strong>이 있다. 모르스키에 오코(코스 C)와 쿠즈니체(코스 B 케이블카 하부)행 버스가 여기서 출발한다.',
      ],
      walkAfter: { mode: '도보 12분', tram: false, text: '역 광장에서 남서쪽 <em>Kościuszki</em> 거리를 따라 약 700m. 끝에서 크루포브키 거리의 북단에 합류한다.' },
    },
    {
      id: 's02', num: '02', order: 2,
      time: '0:15', stay: '약 15분',
      nameKr: '크루포브키 진입 · 하우비인스키 기념물', namePl: 'Krupówki · Pomnik Chałubińskiego',
      lat: 49.2978, lon: 19.9504,
      image: 'zakopane/images/02-krupowki-north.jpg',
      paragraphs: [
        '9회차에서 본 그 거리. <strong>크루포브키(Krupówki)</strong>는 자코파네의 메인 보행자 거리, 약 1km. 시내의 거의 모든 사람의 동선이 이 한 거리에 모인다.',
        '거리에 발을 들이자마자 한 모퉁이에 — <strong>티투스 하우비인스키 기념물(1903)</strong>이 — 서 있다. 9회차 Beat 1의 그 의사. 자코파네 사람들이 그가 죽은 지 14년 후 세운 작품. 폴란드의 한 의사가 한 마을의 한 "아버지"로 기억된 것은 — 그리 흔하지 않은 — 한 풍경이다.',
        '기념물 옆에는 한 명의 <strong>고랄(Górale) 산악인</strong>이 함께 새겨져 있다 — 양치기 모자와 도끼(<em>ciupaga</em>). 자코파네에 모이게 한 폴란드 지식인들 옆에 — 원래 이 자리에 살던 사람들도 — 한 자리를 차지하는 작은 디테일.',
      ],
      walkAfter: { mode: '도보 8분', tram: false, text: '크루포브키 거리를 남쪽으로 약 400m. 거리 중간쯤, 왼편(동쪽)에 황토색 큰 건물이 보인다.' },
    },
    {
      id: 's03', num: '03', order: 3,
      time: '0:35', stay: '약 30분',
      nameKr: '타트라 박물관', namePl: 'Muzeum Tatrzańskie',
      lat: 49.2944, lon: 19.9530,
      image: 'zakopane/images/03-muzeum-tatrzanskie.jpg',
      paragraphs: [
        '<strong>1888년 설립</strong>된 폴란드 가장 오래된 산악 박물관 중 하나. 박물관의 정식 이름이 — <strong>"닥터 티투스 하우비인스키 타트라 박물관"</strong> — 그의 자코파네 한 자리를 다시 한 번 확인시킨다.',
        '전시는 세 갈래 — 첫째 <strong>타트라 산맥의 자연사</strong>(지질·식물·동물), 둘째 <strong>고랄 민속 문화</strong>(목조 건축 모형·민속 의상), 셋째 <strong>자코파네 인물사</strong>(하우비인스키·비트키에비치·시마노프스키 등). 한 박물관 안에서 자코파네의 세 켜를 한 번에 본다.',
        '건물 자체도 자코파네 양식의 한 예. 1922년 — 비트키에비치 사후 7년 — 자코파네 양식으로 새로 지어진 박물관 건물이다.',
        '<strong>관광 팁:</strong> 입장 약 13 PLN. 월요일 휴무. 한 시간이면 충분.',
      ],
      walkAfter: { mode: '도보 2분', tram: false, text: '박물관 정문에서 다시 크루포브키 거리로 — 남쪽으로 약 100m. 거리의 가장 자코파네스러운 노점·식당이 모인 자리.' },
    },
    {
      id: 's04', num: '04', order: 4,
      time: '1:15', stay: '약 45분 (점심)',
      nameKr: '크루포브키 남단 · 오스치펙 점심', namePl: 'Krupówki Południe · Obiad',
      lat: 49.2941, lon: 19.9525,
      image: 'zakopane/images/08-oscypek-stall.jpg',
      paragraphs: [
        '9회차 Beat 4의 그 산악 음식 시간. 크루포브키 거리의 남쪽 끝 근방에 — 가장 자코파네스러운 — 노점과 식당이 모여 있다. 박물관 다음에 한 끼를 — 가장 자코파네답게 — 먹고, 오후의 후반 동선을 가볍게 시작한다.',
        '<strong>오스치펙(Oscypek)</strong>: 양젖 훈제 치즈. 길거리 노점에서 작은 숯불 위에 굽고 크랜베리 잼 곁들임. 약 8–12 PLN. 자코파네에서 한 번은 반드시 만져야 할 한 입.',
        '점심으로는 <ul><li><strong>Kwaśnica</strong> — 양배추 신김치 스튜 + 산악 소시지</li><li><strong>Bryndzowe placki</strong> — 양젖 치즈 감자전</li><li><strong>Pieczona kiełbasa jałowcowa</strong> — 노간주 향 산악 소시지 구이</li><li><strong>Pierogi z bryndzą</strong> — 양젖 치즈 속의 자코파네 피에로기</li><li><strong>Grzane piwo z miodem</strong> — 데운 맥주에 꿀과 향신료 (겨울)</li></ul>',
        '식당 추천: <strong>Karczma Zbójecka</strong>(산악 인테리어), <strong>Bąkowo Zohylina</strong>(자코파네 양식 + 라이브 고랄 음악), <strong>U Wnuka</strong>(1850년대 건물).',
        '<strong>관광 팁:</strong> 점심 시간 13–15시는 줄이 길다. 메인 거리에서 한 블록 들어간 작은 식당이 가격·품질 더 낫기도.',
      ],
      walkAfter: { mode: '도보 7분', tram: false, text: '크루포브키 남단에서 동쪽 골목(<em>Kasprusie</em>)으로 약 400m. 작은 동네 길로 들어선다. 자코파네 양식 빌라들이 한 켜로 나타나기 시작한다.' },
    },
    {
      id: 's05', num: '05', order: 5,
      time: '2:05', stay: '약 30분',
      nameKr: 'Villa Atma · 시마노프스키 박물관', namePl: 'Willa Atma',
      lat: 49.2940, lon: 19.9506,
      image: 'zakopane/images/04-villa-atma.jpg',
      paragraphs: [
        '9회차 Beat 3의 그 자리. 자코파네 양식의 작은 빌라 — <strong>"아트마(Atma)"</strong>는 산스크리트어로 "영혼·자아" — 에서 <strong>카롤 시마노프스키(1882–1937)</strong>가 1930–35년 거주했다.',
        '3회차에서 본 폴란드 20세기 음악의 정점. 그의 가장 유명한 작품 발레 <strong>〈하르나시에(Harnasie)〉</strong>가 이 자리에서 — 타트라 산자락의 도적단 이야기와 고랄 민요를 녹여 — 완성되었다. 박물관 안에서 그 음악이 작게 흘러나온다.',
        '전시는 작곡가의 응접실·서재·피아노가 거의 그대로 재현. 자코파네 양식 가구·고랄 카펫·산을 향한 창. 한 작곡가의 자코파네 5년이 응축된 한 빌라.',
        '<strong>관광 팁:</strong> 입장 약 12 PLN. 화요일 휴무. 30분이면 충분.',
      ],
      walkAfter: { mode: '도보 10분', tram: false, text: 'Kasprusie 거리를 — 작은 강을 건너 — <em>Kościeliska</em> 거리로 진입. 약 500m. 옛 자코파네의 진짜 한 자리.' },
    },
    {
      id: 's06', num: '06', order: 6,
      time: '2:45', stay: '약 15분',
      nameKr: '옛 목조 교회', namePl: 'Stary Kościół (MB Częstochowskiej)',
      lat: 49.2969, lon: 19.9479,
      image: 'zakopane/images/05-stary-kosciol.jpg',
      paragraphs: [
        '<strong>1851년 봉헌</strong>된 자코파네 가장 오래된 교회. 통나무로 지어진 작은 목조 교회. 박공지붕, 나무 십자가, 처마 끝마다 새겨진 산악 문양. 비트키에비치가 1886년 자코파네에 도착해 한 자리를 사로잡힌 그 풍경의 한 원본.',
        '비트키에비치의 자코파네 양식이 — 산악 목조 건축을 폴란드 국민 양식의 후보로 제안한 — 그 시도의 한 출발점에 이 교회가 있었다. 빌라 코리바(1893)보다 42년 먼저, 그러나 같은 형식 어휘의 한 원형.',
        '교회 내부는 작은 본당 한 자리. 통나무 벽이 그대로 노출, 제단도 목조. 폴란드의 가톨릭 교회로서는 가장 단순한 한 자리. 5분이면 충분히 본다.',
        '<strong>관광 팁:</strong> 입장 무료. 미사 중에는 사진 자제.',
      ],
      walkAfter: { mode: '도보 2분', tram: false, text: '교회 바로 옆 — 같은 마당 한 켠 — 에 작은 묘지가 있다. 정문을 통과하면 정거장 7.' },
    },
    {
      id: 's07', num: '07', order: 7,
      time: '3:05', stay: '약 30분',
      nameKr: 'Pęksów Brzyzek 옛 묘지', namePl: 'Cmentarz na Pęksowym Brzyzku',
      lat: 49.2971, lon: 19.9481,
      image: 'zakopane/images/06-peksow-brzyzek.jpg',
      paragraphs: [
        '9회차 Beat 3에서 본 그 자리. 자코파네에서 가장 무거운 한 자리이자 — 폴란드 어디에도 없는 — 한 종류의 묘지. 19세기 후반 이후 자코파네에 깊이 연결된 폴란드인들이 — 자코파네 출신이 아닌 사람도 — 여기에 묻혔다.',
        '한 둘 정도만 — 묘비의 한 자리를 — 짚어본다 (전부 보려 하지 말기를).',
        '<ul><li><strong>스타니스와프 비트키에비치(1851–1915)</strong> — 자코파네 양식의 발명자.</li><li><strong>Witkacy(1885–1939)</strong> — 비트키에비치 아들의 상징적 자리. 9회차의 그 "잘못된 유해" 사연. 묘비는 — 비어 있는 — 한 자리.</li><li><strong>코르넬 마쿠신스키(1884–1953)</strong> — 폴란드 아동문학 작가. <em>코지오웨크 마톨레크</em>.</li><li><strong>브와디스와프 하시오르(1928–1999)</strong> — 폴란드 20세기 후반 조각가.</li><li>자코파네 산악 안내인·등산가들의 묘 — 산에서 죽은 사람들의 한 자리.</li></ul>',
        '묘비의 형식이 다르다. 화강암보다 — 통나무 십자가·산악 도끼 조각·고랄 모티프가 — 많다.',
        '<strong>관광 팁:</strong> 입장 무료. 30분이면 충분. 한 이름을 발음해 보고 가는 것이 좋다.',
      ],
      walkAfter: { mode: '도보 6분', tram: false, text: 'Kościeliska 거리를 — 묘지에서 — 서쪽으로 계속. 약 300m. 거리 양옆에 자코파네 양식 빌라들이 늘어선다.' },
    },
    {
      id: 's08', num: '08', order: 8,
      time: '3:45', stay: '약 30분',
      nameKr: '빌라 코리바 · 자코파네 양식 박물관', namePl: 'Willa Koliba',
      lat: 49.2972, lon: 19.9462,
      image: 'zakopane/images/07-willa-koliba.jpg',
      paragraphs: [
        '9회차 Beat 2에서 본 그 자리. <strong>1893년 비트키에비치가 설계한 자코파네 양식의 첫 작품</strong>. 가파른 박공지붕, 통나무 벽, 처마 끝마다 새겨진 태양·꽃·심장 문양. 폴란드 부르주아의 별장에 양치기 오두막의 형식을 — 의도적으로 — 가져온 한 충돌.',
        '현재 건물은 <strong>"자코파네 양식 박물관"</strong>으로 운영. 비트키에비치의 화가로서의 작품 일부, 자코파네 양식 가구·인테리어, 그리고 비트키에비치 본인의 자코파네 30년이 정리되어 있다.',
        '박물관 2층의 한 응접실은 — 1893년 빌라 코리바 첫 입주 시의 가구 배치를 그대로 복원. 자코파네 양식이 — 종이 위 도면이 아니라 — 한 사람이 실제로 살았던 공간이었다는 것을 만진다.',
        '<strong>관광 팁:</strong> 입장 약 12 PLN. 보통 월요일 휴무.',
      ],
      walkAfter: { mode: '도보 12분', tram: false, text: '빌라 코리바에서 동쪽으로 — Kościeliska 거리를 돌아 — 크루포브키를 거쳐 굴루부프카 케이블카 하부역으로. 약 700m. 거리 끝의 노란 건물.' },
    },
    {
      id: 's09', num: '09', order: 9, terminus: true,
      time: '4:30', stay: '약 1–1.5시간',
      nameKr: '굴루부프카 케이블카 · 종착', namePl: 'Kolej linowo-terenowa na Gubałówkę',
      lat: 49.2987, lon: 19.9521,
      image: 'zakopane/images/09-gubalowka.jpg',
      paragraphs: [
        '<strong>1938년 개통</strong>한 폴란드 가장 오래된 케이블카(<em>kolej linowo-terenowa</em>) 중 하나. 시내 해발 약 850m에서 정상 1,126m까지 약 300m를 5분에 오른다. 산비탈을 따라 달리는 푸니쿨라형.',
        '정상에서 보는 풍경이 자코파네 여행의 한 절정. <strong>건너편에 타트라 산맥 전체가 한 폭의 파노라마로</strong> 펼쳐진다 — 자코파네 시내, 그 너머 카스프로비 비에르흐, 비스코키 비에르흐, 기에반트, 슬로바키아 쪽 봉우리들. 한 화면에 타트라가 다 들어온다.',
        '정상에는 식당·노점·기념품점. 코스 A의 점심을 정거장 4 대신 여기 정상에서 먹는 것도 한 선택.',
        '내려오는 길은 — 케이블카(같은 길) 또는 도보 산책로(약 1시간). 도보 산책로는 자코파네 시내의 다른 면을 보여준다. 산비탈에 흩어진 목조 농가들.',
        '<strong>관광 팁:</strong> 케이블카 왕복 약 35 PLN. 사전 예약 권장(<em>gubalowkakolej.pl</em>). 운영 보통 9:00–18:00. 안개·강풍 시 일시 중단.',
        '<strong>여기서 코스 A — 그리고 10회 시리즈의 한 끝 — 가 마친다.</strong>',
      ],
      walkAfter: null,
    },
  ],
};
